module Errno

  E2BIG = Errno::E2BIG
  EACCES = Errno::EACCES
  EADDRINUSE = Errno::EADDRINUSE
  EADDRNOTAVAIL = Errno::EADDRNOTAVAIL
  EAFNOSUPPORT = Errno::EAFNOSUPPORT
  EAGAIN = Errno::EAGAIN
  EALREADY = Errno::EALREADY
  EBADF = Errno::EBADF
  EBADMSG = Errno::EBADMSG
  EBUSY = Errno::EBUSY
  ECHILD = Errno::ECHILD
  ECONNABORTED = Errno::ECONNABORTED
  ECONNREFUSED = Errno::ECONNREFUSED
  ECONNRESET = Errno::ECONNRESET
  EDEADLK = Errno::EDEADLK
  EDESTADDRREQ = Errno::EDESTADDRREQ
  EDOM = Errno::EDOM
  EDQUOT = Errno::EDQUOT
  EEXIST = Errno::EEXIST
  EFAULT = Errno::EFAULT
  EFBIG = Errno::EFBIG
  EHOSTDOWN = Errno::EHOSTDOWN
  EHOSTUNREACH = Errno::EHOSTUNREACH
  EIDRM = Errno::EIDRM
  EILSEQ = Errno::EILSEQ
  EINPROGRESS = Errno::EINPROGRESS
  EINTR = Errno::EINTR
  EINVAL = Errno::EINVAL
  EIO = Errno::EIO
  EISCONN = Errno::EISCONN
  EISDIR = Errno::EISDIR
  ELOOP = Errno::ELOOP
  EMFILE = Errno::EMFILE
  EMLINK = Errno::EMLINK
  EMSGSIZE = Errno::EMSGSIZE
  EMULTIHOP = Errno::EMULTIHOP
  ENAMETOOLONG = Errno::ENAMETOOLONG
  ENETDOWN = Errno::ENETDOWN
  ENETRESET = Errno::ENETRESET
  ENETUNREACH = Errno::ENETUNREACH
  ENFILE = Errno::ENFILE
  ENOBUFS = Errno::ENOBUFS
  ENODATA = Errno::ENODATA
  ENODEV = Errno::ENODEV
  ENOENT = Errno::ENOENT
  ENOEXEC = Errno::ENOEXEC
  ENOLCK = Errno::ENOLCK
  ENOLINK = Errno::ENOLINK
  ENOMEM = Errno::ENOMEM
  ENOMSG = Errno::ENOMSG
  ENOPROTOOPT = Errno::ENOPROTOOPT
  ENOSPC = Errno::ENOSPC
  ENOSR = Errno::ENOSR
  ENOSTR = Errno::ENOSTR
  ENOSYS = Errno::ENOSYS
  ENOTBLK = Errno::ENOTBLK
  ENOTCONN = Errno::ENOTCONN
  ENOTDIR = Errno::ENOTDIR
  ENOTEMPTY = Errno::ENOTEMPTY
  ENOTSOCK = Errno::ENOTSOCK
  ENOTTY = Errno::ENOTTY
  ENXIO = Errno::ENXIO
  EOPNOTSUPP = Errno::EOPNOTSUPP
  EOVERFLOW = Errno::EOVERFLOW
  EPERM = Errno::EPERM
  EPFNOSUPPORT = Errno::EPFNOSUPPORT
  EPIPE = Errno::EPIPE
  EPROTO = Errno::EPROTO
  EPROTONOSUPPORT = Errno::EPROTONOSUPPORT
  EPROTOTYPE = Errno::EPROTOTYPE
  ERANGE = Errno::ERANGE
  EREMOTE = Errno::EREMOTE
  EROFS = Errno::EROFS
  ESHUTDOWN = Errno::ESHUTDOWN
  ESOCKTNOSUPPORT = Errno::ESOCKTNOSUPPORT
  ESPIPE = Errno::ESPIPE
  ESRCH = Errno::ESRCH
  ESTALE = Errno::ESTALE
  ETIME = Errno::ETIME
  ETIMEDOUT = Errno::ETIMEDOUT
  ETOOMANYREFS = Errno::ETOOMANYREFS
  ETXTBSY = Errno::ETXTBSY
  EUSERS = Errno::EUSERS
  EWOULDBLOCK = Errno::EAGAIN
  EXDEV = Errno::EXDEV



  protected


  private

end
